name: Enterprise Go CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Verify Dependencies
      run: go mod tidy

    - name: Run Go Vet (Static Analysis)
      run: go vet ./...

    - name: Build Application
      run: go build -v ./...